version: "3.4"
services:
  gpubsub:
    image: google/cloud-sdk:latest
    ports:
      - "8793:8793"
    entrypoint:
      - gcloud
      - beta
      - emulators
      - pubsub
      - start
      - "--host-port=0.0.0.0:8793"
